[workspace]
members = [
    "crates/psd2ase-core",
    "crates/psd2ase-cli",
    "tools/rust-psd-probe",
]
default-members = [
    "crates/psd2ase-core",
    "crates/psd2ase-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.88"

[workspace.dependencies]
ag-psd = { git = "https://github.com/minerva-studio/ag-psd-rs.git", rev = "c250b11" }
aseprite-io = "0.2.0"

[workspace.lints.rust]
unsafe_code = "forbid"
