[package]
name = "aseprite-psd"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aseprite-psd-core = { path = "../aseprite-psd-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
aseprite-io = { workspace = true }

[lints]
workspace = true
